In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3]) #vector(1차원)
print('array1 type: ', type(array1))
print('array1 shape: ', array1.shape)

array2= np.array([ [1,2,3],[3,4,5]])
print('array2 type: ', type(array2))
print('array2 shape: ', array2.shape)

array3= np.array([[1,2,3]]) #2차원
print('array3 type: ', type(array3))
print('array3 shape: ', array3.shape)

array1 type:  <class 'numpy.ndarray'>
array1 shape:  (3,)
array2 type:  <class 'numpy.ndarray'>
array2 shape:  (2, 3)
array3 type:  <class 'numpy.ndarray'>
array3 shape:  (1, 3)


In [8]:
print('array1: {:0}차원\n\
array2: {:1}차원\n\
array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원
array2: 2차원
array3:  2차원


In [10]:
list1= [1,2,3]
print(type(list1))

array1= np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [11]:
list2= [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3=[1,2, 3.0]
array3= np.array(list3) # 모든 원소가 float이 됨..
print(array3, array3.dtype) 

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [12]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


# ndarray를 편리하게 생성하기 - arange, zeros, ones

In [14]:
sequence_array = np.arange(10) # 0~9
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape) 

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [15]:
zero_array = np.zeros( (3,2), dtype='int32')
print(zero_array)
print('shape: {}\n dtype: {}'.format(zero_array.shape, zero_array.dtype))

[[0 0]
 [0 0]
 [0 0]]
shape: (3, 2)
 dtype: int32


In [16]:
one_array = np.ones( (3,2), dtype='int32')
print(one_array)
print('shape: {}\n dtype: {}'.format(one_array.shape, one_array.dtype))

[[1 1]
 [1 1]
 [1 1]]
shape: (3, 2)
 dtype: int32


# ndarray의 차원과 크기를 변경하는 reshape()

In [19]:
array1 = np.arange(10)
print('array1:\n{}\n'.format(array1))

array2= array1.reshape(2,5)
print('array2:\n{}\n'.format(array2))

array3= array2.T # Transpose array2 
print('array3:\n{}\n'.format(array3))

array3_2 = array2.reshape(5,2)
print('array3_2:\n{}'.format(array3_2))

array1:
[0 1 2 3 4 5 6 7 8 9]

array2:
[[0 1 2 3 4]
 [5 6 7 8 9]]

array3:
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]

array3_2:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [24]:
array1= np.arange(10)
print(array1,'\n')

array2= array1.reshape(-1, 5) # ?행 x 5열 = 10 , ?=2
print('array2.shape: ', array2.shape)
print('array2: ', array2,'\n')

array3= array1.reshape(5,-1)#  5 행x ?열=10 , ?=2
print('array3.shape: ', array3.shape)
print('array3: ', array3)

[0 1 2 3 4 5 6 7 8 9] 

array2.shape:  (2, 5)
array2:  [[0 1 2 3 4]
 [5 6 7 8 9]] 

array3.shape:  (5, 2)
array3:  [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [25]:
array4= array1.reshape(-1,4) # ?행 x 4열= 10, ?=2.5
print('array4.shape: ', array4.shape) # 행과 열은 양의정수로 나타낸다.

ValueError: cannot reshape array of size 10 into shape (4)

In [26]:
array1= np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape: ', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6= array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6.shape: ', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape:  (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6.shape:  (8, 1)


# 넘파이의 ndarray의 데이터세트 선택하기 - 인덱싱(indexing)

In [27]:
# 1부터 9까지 1차원 ndarray생성
array1= np.arange( start=1, stop=10)
print('array1: ', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value=array1[2]
print('value: ', value)
print(type(value))

array1:  [1 2 3 4 5 6 7 8 9]
value:  3
<class 'numpy.int32'>


In [30]:
print('맨 뒤의 값: {}, 맨뒤에서 두번째 값: {}'.format(array1[-1], array1[-2]))

맨 뒤의 값: 9, 맨뒤에서 두번째 값: 8


## 다차원 ndarray에서 단일값을 추출하기

In [31]:
array1d = np.arange(start=1, stop=10) #[ 1,2,3,4,5,6,7,8,9]
array2d = array1d.reshape(3,3) #3행 3열로 나타냄
print(array2d)

print('(row=0, col=0) index 가리키는 값: ', array2d[0,0])
print('(row=0, col=1) index 가리키는 값: ', array2d[0,1])
print('(row=1, col=0) index 가리키는 값: ', array2d[1,0])
print('(row=1, col=1) index 가리키는 값: ', array2d[1,1])
print('(row=2, col=2) index 가리키는 값: ', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값:  1
(row=0, col=1) index 가리키는 값:  2
(row=1, col=0) index 가리키는 값:  4
(row=1, col=1) index 가리키는 값:  5
(row=2, col=2) index 가리키는 값:  9


# 슬라이싱(slicing)

In [33]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))


array4= array1[:3]
print(array4)

array5 =array1[3:]
print(array5)

array6= array1[:]
print(array6)

[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [35]:

array1d= np.arange(start=1, stop=10)
array2d= array1d.reshape(3,3)
print('array2d:\n', array2d, '\n')

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2], '\n')
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3], '\n')

print('array2d[1:3, :]\n', array2d[1:3, :], '\n')
print('array2d[:, :]\n', array2d[:, :], '\n')

print('array2d[:2, 1:]\n', array2d[:2, 1:], '\n')
print('array2d[:2, 0]\n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

array2d[0:2, 0:2]
 [[1 2]
 [4 5]] 

array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]] 

array2d[1:3, :]
 [[4 5 6]
 [7 8 9]] 

array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

array2d[:2, 1:]
 [[2 3]
 [5 6]] 

array2d[:2, 0]
 [1 4]


# Fancy Indexing

In [38]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[ [0,1], 2]
print('array2d[ [0,1], 2]=> ', array3)

array4= array2d[ [0,1], 0:2]
print('array2d[ [0,1], 0:2]\n', array4,'\n')

array5= array2d[[0,1]]
print('array2d[[0,1]]\n', array5)

array2d[ [0,1], 2]=>  [3 6]
array2d[ [0,1], 0:2]
 [[1 2]
 [4 5]] 

array2d[[0,1]]
 [[1 2 3]
 [4 5 6]]


# Boolean Indexing

In [39]:
array1d=  np.arange(start=1, stop=10)

# [ ] 안에 array1d > 5 Boolean indexing을 적용한다.
array3= array1d[ array1d>5 ]
print('array1d >5 boolean indexing result: \n', array3)

array1d >5 boolean indexing result: 
 [6 7 8 9]


In [41]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [43]:
boolean_indexes= np.array(array1d>5)
array3= array1d[boolean_indexes]
print('filtered boolean index result: ', array3)

filtered boolean index result:  [6 7 8 9]


In [47]:
indexes= np.arange(start=5,stop=9) # [5,6,7,8]
array4 =array1d[indexes]
print('general index result: ', array4)

general index result:  [6 7 8 9]


# 행렬의 정렬: sort(), argsort()

In [48]:
org_array = np.array([3,1,9,5])
print('원본 행렬: ', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬: ', sort_array1)

# ndarray.sort() 로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬: ', sort_array2)
print('org_array.sort() 호출 후 원본 행렬: ', org_array)

원본 행렬:  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬:  [1 3 5 9]
org_array.sort() 호출 후 반환된 행렬:  None
org_array.sort() 호출 후 원본 행렬:  [1 3 5 9]


In [49]:
# 내림차순으로 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬; ', sort_array1_desc)

내림차순으로 정렬;  [9 5 3 1]


In [51]:
# 행렬이 2차원 이상일 경우에 axis 축값 설정을 통해
# row방향, column 방향으로 정렬을 수행할 수 있다.

array2d = np.array([ [8,12], [7,1] ])
sort_array2d_axis0 =np.sort(array2d, axis=0)
print('row방향- axis=0 - 방향으로 정렬: \n', sort_array2d_axis0,'\n')

sort_array2d_axis1= np.sort(array2d, axis=1)
print('column방향- axis=1 - 방향으로 정렬: \n', sort_array2d_axis1)

row방향- axis=0 - 방향으로 정렬: 
 [[ 7  1]
 [ 8 12]] 

column방향- axis=1 - 방향으로 정렬: 
 [[ 8 12]
 [ 1  7]]


## 정렬된 행렬의 인덱스를 반환하기

In [52]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스: ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스:  [1 0 3 2]


In [55]:
org_array = np.array([3,1,9,5])
sort_indices= np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스: ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스:  [1 0 3 2]


In [62]:
name_array = ['John', 'Mike', 'Sarah', 'Kate', 'Samuel']
score_array = [78, 95, 84, 98, 88]

rank_score = np.argsort(score_array)[::-1] #내림차순
print('highest-score-index:', rank_score)

for i in range(0,3):
    print(i+1,'등: ', name_array[rank_score[i]], '=> {}점'.format(score_array[rank_score[i]]))

highest-score-index: [3 1 4 2 0]
1 등:  Kate => 98점
2 등:  Mike => 95점
3 등:  Samuel => 88점


# 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

## 행렬 내적(행렬 곱)

In [67]:
A=np.arange(start=1, stop=7).reshape(2,3)
print('A:\n{}\n'.format(A))

B=np.arange(start=7, stop=13).reshape(3,2)
print('B:\n{}\n'.format(B))

# A* B 내적결과
A_dot_B= np.dot(A,B)
print('np.dot(A,B)=\n{}'.format(A_dot_B))

A:
[[1 2 3]
 [4 5 6]]

B:
[[ 7  8]
 [ 9 10]
 [11 12]]

np.dot(A,B)=
[[ 58  64]
 [139 154]]


# 전치행렬(Transpose)

In [68]:
A= np.arange(start=1, stop=5).reshape(2,2)
print(A,'\n')

AT= A.T #np.transpose(A)
print(AT)

[[1 2]
 [3 4]] 

[[1 3]
 [2 4]]
